# Generated by Django 5.2.5 on 2025-09-05 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_reader_firstname_remove_reader_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='reader',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='reader',
            name='phone_no',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
